### ISSUE TITLE
cannot import boost symbols

### ISSUE THREAD

**Issue by esheldon** [reikonakajima/FDNT#26]
I'm getting an error trying to import

``` python
>>> import fdnt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/ki/esheldon/miniconda/envs/nsim-work/lib/python2.7/site-packages/fdnt/__init__.py", line 2, in <module>
    from _fdnt import *
ImportError: /u/ki/esheldon/miniconda/envs/nsim-work/lib/python2.7/site-packages/fdnt/_fdnt.so: undefined symbol: _ZTIN5boost6python15instance_holderE
```

I've got an install of galsim that works, and I used the same scons call for installing fdnt.

```
scons PREFIX=/some/path  install
```

 so I don't think this is anything fundamentally wrong with my system

**Comment by reikonakajima** [comment]
I'm not really sure if I can help you, but from the error message it seems like there is a missing link to the Boost library.

**Comment by reikonakajima** [comment]
I mean, the scons probably needs to have the BOOST_DIR parameter specified.

**Comment by esheldon** [comment]
On 8/27/15, Reiko Nakajima <notifications@github.com> wrote:
> I mean, the scons probably needs to have the BOOST_DIR parameter specified.

the code compiles fine, there is only a problem at runtime.  THe boost
libraries and headers are in the "usual" places under /usr

-e

-- 
Erin Scott Sheldon
Brookhaven National Laboratory erin dot sheldon at gmail dot com

**Comment by gbernstein** [comment]
The LD_LIBRARY_PATH will also need to have the BOOST_DIR in it.  Beyond that I can't help, since I don't know anything about Boost Python where this error is coming from.

**Comment by esheldon** [comment]
On 8/27/15, Gary Bernstein <notifications@github.com> wrote:
> The LD_LIBRARY_PATH will also need to have the BOOST_DIR in it.  Beyond that
> I can't help, since I don't know anything about Boost Python where this
> error is coming from.

Since boost is under /usr no environment variables need to be modified.

I'll ask Mike since he seems to have got this working "out of the box"
for galsim.

**Comment by esheldon** [comment]
The problem seems to have been python.  The default_python trick
wasn't working (although I see the same code in the galsim SConstruct
so I'm not sure what the problem is)

I sent PYTHON= and it worked

**Comment by reikonakajima** [comment]
Great.  Closing issue.

**Comment by esheldon** [comment]
OK, it works for me. But it might be useful to include whatever fixes for this galsim has in it's SConstruct, to automatically deal with python

**Comment by reikonakajima** [comment]
> But it might be useful to include whatever fixes for this galsim has in it's SConstruct, 

I don't know that fix galsim has to deal with this.
@rmjarvis : would you happen to know?

**Comment by rmjarvis** [comment]
GalSim figures out the default python to use here:

https://github.com/GalSim-developers/GalSim/blob/releases/1.3/SConstruct#L1749

which is different from what you have here:

https://github.com/reikonakajima/FDNT/blob/master/SConstruct#L1777

I forget why `/usr/bin/env python` isn't necessarily appropriate, but I think it had to do with the environment internal to SCons not being the same as the one the user will experience on the command line, even when `IMPORT_ENV = True`.  I think this was particularly a problem when using modules, but I don't know if I ever figured it out beyond that.

**Comment by reikonakajima** [comment]
Thanks Mike!  I"ve put the changes in.

**Comment by reikonakajima** [comment]
It seems to compile OK, so I'm just going to push to master.  

Merged and pushed.  Closing.
